// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/chatbot.proto

package chatbot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatbotService_Chat_FullMethodName              = "/chatbot.ChatbotService/Chat"
	ChatbotService_GetSession_FullMethodName        = "/chatbot.ChatbotService/GetSession"
	ChatbotService_ClearSession_FullMethodName      = "/chatbot.ChatbotService/ClearSession"
	ChatbotService_GetProviderStatus_FullMethodName = "/chatbot.ChatbotService/GetProviderStatus"
	ChatbotService_HealthCheck_FullMethodName       = "/chatbot.ChatbotService/HealthCheck"
)

// ChatbotServiceClient is the client API for ChatbotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Chatbot service definition
type ChatbotServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	GetSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error)
	GetProviderStatus(ctx context.Context, in *ProviderStatusRequest, opts ...grpc.CallOption) (*ProviderStatusResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type chatbotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotServiceClient(cc grpc.ClientConnInterface) ChatbotServiceClient {
	return &chatbotServiceClient{cc}
}

func (c *chatbotServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, ChatbotService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) GetSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, ChatbotService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSessionResponse)
	err := c.cc.Invoke(ctx, ChatbotService_ClearSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) GetProviderStatus(ctx context.Context, in *ProviderStatusRequest, opts ...grpc.CallOption) (*ProviderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderStatusResponse)
	err := c.cc.Invoke(ctx, ChatbotService_GetProviderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ChatbotService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatbotServiceServer is the server API for ChatbotService service.
// All implementations must embed UnimplementedChatbotServiceServer
// for forward compatibility.
//
// Chatbot service definition
type ChatbotServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	GetSession(context.Context, *SessionRequest) (*SessionResponse, error)
	ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error)
	GetProviderStatus(context.Context, *ProviderStatusRequest) (*ProviderStatusResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedChatbotServiceServer()
}

// UnimplementedChatbotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatbotServiceServer struct{}

func (UnimplementedChatbotServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatbotServiceServer) GetSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedChatbotServiceServer) ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearSession not implemented")
}
func (UnimplementedChatbotServiceServer) GetProviderStatus(context.Context, *ProviderStatusRequest) (*ProviderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderStatus not implemented")
}
func (UnimplementedChatbotServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedChatbotServiceServer) mustEmbedUnimplementedChatbotServiceServer() {}
func (UnimplementedChatbotServiceServer) testEmbeddedByValue()                        {}

// UnsafeChatbotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatbotServiceServer will
// result in compilation errors.
type UnsafeChatbotServiceServer interface {
	mustEmbedUnimplementedChatbotServiceServer()
}

func RegisterChatbotServiceServer(s grpc.ServiceRegistrar, srv ChatbotServiceServer) {
	// If the following call panics, it indicates UnimplementedChatbotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatbotService_ServiceDesc, srv)
}

func _ChatbotService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).GetSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_ClearSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).ClearSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_ClearSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).ClearSession(ctx, req.(*ClearSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_GetProviderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).GetProviderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_GetProviderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).GetProviderStatus(ctx, req.(*ProviderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatbotService_ServiceDesc is the grpc.ServiceDesc for ChatbotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatbotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatbot.ChatbotService",
	HandlerType: (*ChatbotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _ChatbotService_Chat_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _ChatbotService_GetSession_Handler,
		},
		{
			MethodName: "ClearSession",
			Handler:    _ChatbotService_ClearSession_Handler,
		},
		{
			MethodName: "GetProviderStatus",
			Handler:    _ChatbotService_GetProviderStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ChatbotService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/chatbot.proto",
}
