// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/confession.proto

package confession

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Submit confession
type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SubmittedBy   string                 `protobuf:"bytes,4,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"` // Anonymous - not stored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SubmitRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SubmitRequest) GetSubmittedBy() string {
	if x != nil {
		return x.SubmittedBy
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfessionId  int32                  `protobuf:"varint,3,opt,name=confession_id,json=confessionId,proto3" json:"confession_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitResponse) GetConfessionId() int32 {
	if x != nil {
		return x.ConfessionId
	}
	return 0
}

// Approve confession
type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ConfessionId  int32                  `protobuf:"varint,2,opt,name=confession_id,json=confessionId,proto3" json:"confession_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,3,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ApproveRequest) GetConfessionId() int32 {
	if x != nil {
		return x.ConfessionId
	}
	return 0
}

func (x *ApproveRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfessionNumber int32                  `protobuf:"varint,3,opt,name=confession_number,json=confessionNumber,proto3" json:"confession_number,omitempty"`
	ChannelId        string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveResponse) GetConfessionNumber() int32 {
	if x != nil {
		return x.ConfessionNumber
	}
	return 0
}

func (x *ApproveResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ApproveResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Reject confession
type RejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ConfessionId  int32                  `protobuf:"varint,2,opt,name=confession_id,json=confessionId,proto3" json:"confession_id,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,3,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{4}
}

func (x *RejectRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *RejectRequest) GetConfessionId() int32 {
	if x != nil {
		return x.ConfessionId
	}
	return 0
}

func (x *RejectRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *RejectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{5}
}

func (x *RejectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Reply to confession
type ReplyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GuildId          string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ConfessionNumber int32                  `protobuf:"varint,2,opt,name=confession_number,json=confessionNumber,proto3" json:"confession_number,omitempty"`
	ReplyContent     string                 `protobuf:"bytes,3,opt,name=reply_content,json=replyContent,proto3" json:"reply_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyRequest) Reset() {
	*x = ReplyRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyRequest) ProtoMessage() {}

func (x *ReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyRequest.ProtoReflect.Descriptor instead.
func (*ReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ReplyRequest) GetConfessionNumber() int32 {
	if x != nil {
		return x.ConfessionNumber
	}
	return 0
}

func (x *ReplyRequest) GetReplyContent() string {
	if x != nil {
		return x.ReplyContent
	}
	return ""
}

type ReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyResponse) Reset() {
	*x = ReplyResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyResponse) ProtoMessage() {}

func (x *ReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyResponse.ProtoReflect.Descriptor instead.
func (*ReplyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReplyResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Get pending confessions
type GetPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingRequest) Reset() {
	*x = GetPendingRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRequest) ProtoMessage() {}

func (x *GetPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRequest.ProtoReflect.Descriptor instead.
func (*GetPendingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{8}
}

func (x *GetPendingRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confessions   []*Confession          `protobuf:"bytes,1,rep,name=confessions,proto3" json:"confessions,omitempty"`
	TotalPending  int32                  `protobuf:"varint,2,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingResponse) Reset() {
	*x = GetPendingResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingResponse) ProtoMessage() {}

func (x *GetPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingResponse.ProtoReflect.Descriptor instead.
func (*GetPendingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{9}
}

func (x *GetPendingResponse) GetConfessions() []*Confession {
	if x != nil {
		return x.Confessions
	}
	return nil
}

func (x *GetPendingResponse) GetTotalPending() int32 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

// Get settings
type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{10}
}

func (x *GetSettingsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{11}
}

func (x *GetSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Update settings
type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Settings      *Settings              `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSettingsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *UpdateSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Settings      *Settings              `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_confession_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_confession_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type Confession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GuildId          string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ConfessionNumber int32                  `protobuf:"varint,3,opt,name=confession_number,json=confessionNumber,proto3" json:"confession_number,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedAt      string                 `protobuf:"bytes,7,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ApprovedAt       string                 `protobuf:"bytes,8,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Confession) Reset() {
	*x = Confession{}
	mi := &file_api_proto_confession_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confession) ProtoMessage() {}

func (x *Confession) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confession.ProtoReflect.Descriptor instead.
func (*Confession) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{16}
}

func (x *Confession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Confession) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Confession) GetConfessionNumber() int32 {
	if x != nil {
		return x.ConfessionNumber
	}
	return 0
}

func (x *Confession) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Confession) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Confession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Confession) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *Confession) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

type Settings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GuildId             string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Enabled             bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ModChannelId        string                 `protobuf:"bytes,3,opt,name=mod_channel_id,json=modChannelId,proto3" json:"mod_channel_id,omitempty"`
	ConfessionChannelId string                 `protobuf:"bytes,4,opt,name=confession_channel_id,json=confessionChannelId,proto3" json:"confession_channel_id,omitempty"`
	RequireApproval     bool                   `protobuf:"varint,5,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	AllowImages         bool                   `protobuf:"varint,6,opt,name=allow_images,json=allowImages,proto3" json:"allow_images,omitempty"`
	MaxLength           int32                  `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_api_proto_confession_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_confession_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_api_proto_confession_proto_rawDescGZIP(), []int{17}
}

func (x *Settings) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Settings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Settings) GetModChannelId() string {
	if x != nil {
		return x.ModChannelId
	}
	return ""
}

func (x *Settings) GetConfessionChannelId() string {
	if x != nil {
		return x.ConfessionChannelId
	}
	return ""
}

func (x *Settings) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *Settings) GetAllowImages() bool {
	if x != nil {
		return x.AllowImages
	}
	return false
}

func (x *Settings) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

var File_api_proto_confession_proto protoreflect.FileDescriptor

const file_api_proto_confession_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/confession.proto\x12\n" +
	"confession\"\x84\x01\n" +
	"\rSubmitRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12!\n" +
	"\fsubmitted_by\x18\x04 \x01(\tR\vsubmittedBy\"i\n" +
	"\x0eSubmitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rconfession_id\x18\x03 \x01(\x05R\fconfessionId\"q\n" +
	"\x0eApproveRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12#\n" +
	"\rconfession_id\x18\x02 \x01(\x05R\fconfessionId\x12\x1f\n" +
	"\vapproved_by\x18\x03 \x01(\tR\n" +
	"approvedBy\"\xb0\x01\n" +
	"\x0fApproveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11confession_number\x18\x03 \x01(\x05R\x10confessionNumber\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\"\x88\x01\n" +
	"\rRejectRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12#\n" +
	"\rconfession_id\x18\x02 \x01(\x05R\fconfessionId\x12\x1f\n" +
	"\vrejected_by\x18\x03 \x01(\tR\n" +
	"rejectedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"D\n" +
	"\x0eRejectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\fReplyRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12+\n" +
	"\x11confession_number\x18\x02 \x01(\x05R\x10confessionNumber\x12#\n" +
	"\rreply_content\x18\x03 \x01(\tR\freplyContent\"b\n" +
	"\rReplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\".\n" +
	"\x11GetPendingRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"s\n" +
	"\x12GetPendingResponse\x128\n" +
	"\vconfessions\x18\x01 \x03(\v2\x16.confession.ConfessionR\vconfessions\x12#\n" +
	"\rtotal_pending\x18\x02 \x01(\x05R\ftotalPending\"/\n" +
	"\x12GetSettingsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"G\n" +
	"\x13GetSettingsResponse\x120\n" +
	"\bsettings\x18\x01 \x01(\v2\x14.confession.SettingsR\bsettings\"d\n" +
	"\x15UpdateSettingsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x120\n" +
	"\bsettings\x18\x02 \x01(\v2\x14.confession.SettingsR\bsettings\"~\n" +
	"\x16UpdateSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bsettings\x18\x03 \x01(\v2\x14.confession.SettingsR\bsettings\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xf7\x01\n" +
	"\n" +
	"Confession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12+\n" +
	"\x11confession_number\x18\x03 \x01(\x05R\x10confessionNumber\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\fsubmitted_at\x18\a \x01(\tR\vsubmittedAt\x12\x1f\n" +
	"\vapproved_at\x18\b \x01(\tR\n" +
	"approvedAt\"\x86\x02\n" +
	"\bSettings\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12$\n" +
	"\x0emod_channel_id\x18\x03 \x01(\tR\fmodChannelId\x122\n" +
	"\x15confession_channel_id\x18\x04 \x01(\tR\x13confessionChannelId\x12)\n" +
	"\x10require_approval\x18\x05 \x01(\bR\x0frequireApproval\x12!\n" +
	"\fallow_images\x18\x06 \x01(\bR\vallowImages\x12\x1d\n" +
	"\n" +
	"max_length\x18\a \x01(\x05R\tmaxLength2\xdd\x04\n" +
	"\x11ConfessionService\x12?\n" +
	"\x06Submit\x12\x19.confession.SubmitRequest\x1a\x1a.confession.SubmitResponse\x12B\n" +
	"\aApprove\x12\x1a.confession.ApproveRequest\x1a\x1b.confession.ApproveResponse\x12?\n" +
	"\x06Reject\x12\x19.confession.RejectRequest\x1a\x1a.confession.RejectResponse\x12<\n" +
	"\x05Reply\x12\x18.confession.ReplyRequest\x1a\x19.confession.ReplyResponse\x12K\n" +
	"\n" +
	"GetPending\x12\x1d.confession.GetPendingRequest\x1a\x1e.confession.GetPendingResponse\x12N\n" +
	"\vGetSettings\x12\x1e.confession.GetSettingsRequest\x1a\x1f.confession.GetSettingsResponse\x12W\n" +
	"\x0eUpdateSettings\x12!.confession.UpdateSettingsRequest\x1a\".confession.UpdateSettingsResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.confession.HealthCheckRequest\x1a\x1f.confession.HealthCheckResponseB2Z0github.com/nerufuyo/nerubot/api/proto/confessionb\x06proto3"

var (
	file_api_proto_confession_proto_rawDescOnce sync.Once
	file_api_proto_confession_proto_rawDescData []byte
)

func file_api_proto_confession_proto_rawDescGZIP() []byte {
	file_api_proto_confession_proto_rawDescOnce.Do(func() {
		file_api_proto_confession_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_confession_proto_rawDesc), len(file_api_proto_confession_proto_rawDesc)))
	})
	return file_api_proto_confession_proto_rawDescData
}

var file_api_proto_confession_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_confession_proto_goTypes = []any{
	(*SubmitRequest)(nil),          // 0: confession.SubmitRequest
	(*SubmitResponse)(nil),         // 1: confession.SubmitResponse
	(*ApproveRequest)(nil),         // 2: confession.ApproveRequest
	(*ApproveResponse)(nil),        // 3: confession.ApproveResponse
	(*RejectRequest)(nil),          // 4: confession.RejectRequest
	(*RejectResponse)(nil),         // 5: confession.RejectResponse
	(*ReplyRequest)(nil),           // 6: confession.ReplyRequest
	(*ReplyResponse)(nil),          // 7: confession.ReplyResponse
	(*GetPendingRequest)(nil),      // 8: confession.GetPendingRequest
	(*GetPendingResponse)(nil),     // 9: confession.GetPendingResponse
	(*GetSettingsRequest)(nil),     // 10: confession.GetSettingsRequest
	(*GetSettingsResponse)(nil),    // 11: confession.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),  // 12: confession.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil), // 13: confession.UpdateSettingsResponse
	(*HealthCheckRequest)(nil),     // 14: confession.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 15: confession.HealthCheckResponse
	(*Confession)(nil),             // 16: confession.Confession
	(*Settings)(nil),               // 17: confession.Settings
}
var file_api_proto_confession_proto_depIdxs = []int32{
	16, // 0: confession.GetPendingResponse.confessions:type_name -> confession.Confession
	17, // 1: confession.GetSettingsResponse.settings:type_name -> confession.Settings
	17, // 2: confession.UpdateSettingsRequest.settings:type_name -> confession.Settings
	17, // 3: confession.UpdateSettingsResponse.settings:type_name -> confession.Settings
	0,  // 4: confession.ConfessionService.Submit:input_type -> confession.SubmitRequest
	2,  // 5: confession.ConfessionService.Approve:input_type -> confession.ApproveRequest
	4,  // 6: confession.ConfessionService.Reject:input_type -> confession.RejectRequest
	6,  // 7: confession.ConfessionService.Reply:input_type -> confession.ReplyRequest
	8,  // 8: confession.ConfessionService.GetPending:input_type -> confession.GetPendingRequest
	10, // 9: confession.ConfessionService.GetSettings:input_type -> confession.GetSettingsRequest
	12, // 10: confession.ConfessionService.UpdateSettings:input_type -> confession.UpdateSettingsRequest
	14, // 11: confession.ConfessionService.HealthCheck:input_type -> confession.HealthCheckRequest
	1,  // 12: confession.ConfessionService.Submit:output_type -> confession.SubmitResponse
	3,  // 13: confession.ConfessionService.Approve:output_type -> confession.ApproveResponse
	5,  // 14: confession.ConfessionService.Reject:output_type -> confession.RejectResponse
	7,  // 15: confession.ConfessionService.Reply:output_type -> confession.ReplyResponse
	9,  // 16: confession.ConfessionService.GetPending:output_type -> confession.GetPendingResponse
	11, // 17: confession.ConfessionService.GetSettings:output_type -> confession.GetSettingsResponse
	13, // 18: confession.ConfessionService.UpdateSettings:output_type -> confession.UpdateSettingsResponse
	15, // 19: confession.ConfessionService.HealthCheck:output_type -> confession.HealthCheckResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_confession_proto_init() }
func file_api_proto_confession_proto_init() {
	if File_api_proto_confession_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_confession_proto_rawDesc), len(file_api_proto_confession_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_confession_proto_goTypes,
		DependencyIndexes: file_api_proto_confession_proto_depIdxs,
		MessageInfos:      file_api_proto_confession_proto_msgTypes,
	}.Build()
	File_api_proto_confession_proto = out.File
	file_api_proto_confession_proto_goTypes = nil
	file_api_proto_confession_proto_depIdxs = nil
}
