// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/roast.proto

package roast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoastService_TrackActivity_FullMethodName  = "/roast.RoastService/TrackActivity"
	RoastService_GenerateRoast_FullMethodName  = "/roast.RoastService/GenerateRoast"
	RoastService_GetProfile_FullMethodName     = "/roast.RoastService/GetProfile"
	RoastService_GetLeaderboard_FullMethodName = "/roast.RoastService/GetLeaderboard"
	RoastService_GetStats_FullMethodName       = "/roast.RoastService/GetStats"
	RoastService_HealthCheck_FullMethodName    = "/roast.RoastService/HealthCheck"
)

// RoastServiceClient is the client API for RoastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Roast service definition
type RoastServiceClient interface {
	TrackActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityResponse, error)
	GenerateRoast(ctx context.Context, in *RoastRequest, opts ...grpc.CallOption) (*RoastResponse, error)
	GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type roastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoastServiceClient(cc grpc.ClientConnInterface) RoastServiceClient {
	return &roastServiceClient{cc}
}

func (c *roastServiceClient) TrackActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityResponse)
	err := c.cc.Invoke(ctx, RoastService_TrackActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roastServiceClient) GenerateRoast(ctx context.Context, in *RoastRequest, opts ...grpc.CallOption) (*RoastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoastResponse)
	err := c.cc.Invoke(ctx, RoastService_GenerateRoast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roastServiceClient) GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, RoastService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roastServiceClient) GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardResponse)
	err := c.cc.Invoke(ctx, RoastService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roastServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, RoastService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roastServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RoastService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoastServiceServer is the server API for RoastService service.
// All implementations must embed UnimplementedRoastServiceServer
// for forward compatibility.
//
// Roast service definition
type RoastServiceServer interface {
	TrackActivity(context.Context, *ActivityRequest) (*ActivityResponse, error)
	GenerateRoast(context.Context, *RoastRequest) (*RoastResponse, error)
	GetProfile(context.Context, *ProfileRequest) (*ProfileResponse, error)
	GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRoastServiceServer()
}

// UnimplementedRoastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoastServiceServer struct{}

func (UnimplementedRoastServiceServer) TrackActivity(context.Context, *ActivityRequest) (*ActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackActivity not implemented")
}
func (UnimplementedRoastServiceServer) GenerateRoast(context.Context, *RoastRequest) (*RoastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRoast not implemented")
}
func (UnimplementedRoastServiceServer) GetProfile(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedRoastServiceServer) GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedRoastServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRoastServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRoastServiceServer) mustEmbedUnimplementedRoastServiceServer() {}
func (UnimplementedRoastServiceServer) testEmbeddedByValue()                      {}

// UnsafeRoastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoastServiceServer will
// result in compilation errors.
type UnsafeRoastServiceServer interface {
	mustEmbedUnimplementedRoastServiceServer()
}

func RegisterRoastServiceServer(s grpc.ServiceRegistrar, srv RoastServiceServer) {
	// If the following call panics, it indicates UnimplementedRoastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoastService_ServiceDesc, srv)
}

func _RoastService_TrackActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).TrackActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_TrackActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).TrackActivity(ctx, req.(*ActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoastService_GenerateRoast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).GenerateRoast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_GenerateRoast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).GenerateRoast(ctx, req.(*RoastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoastService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).GetProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoastService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).GetLeaderboard(ctx, req.(*LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoastService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoastService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoastServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoastService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoastServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoastService_ServiceDesc is the grpc.ServiceDesc for RoastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roast.RoastService",
	HandlerType: (*RoastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackActivity",
			Handler:    _RoastService_TrackActivity_Handler,
		},
		{
			MethodName: "GenerateRoast",
			Handler:    _RoastService_GenerateRoast_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _RoastService_GetProfile_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _RoastService_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _RoastService_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RoastService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/roast.proto",
}
