// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/roast.proto

package roast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityType int32

const (
	ActivityType_MESSAGE  ActivityType = 0
	ActivityType_REACTION ActivityType = 1
	ActivityType_VOICE    ActivityType = 2
	ActivityType_COMMAND  ActivityType = 3
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "MESSAGE",
		1: "REACTION",
		2: "VOICE",
		3: "COMMAND",
	}
	ActivityType_value = map[string]int32{
		"MESSAGE":  0,
		"REACTION": 1,
		"VOICE":    2,
		"COMMAND":  3,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_roast_proto_enumTypes[0].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_api_proto_roast_proto_enumTypes[0]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{0}
}

type LeaderboardType int32

const (
	LeaderboardType_MESSAGES   LeaderboardType = 0
	LeaderboardType_REACTIONS  LeaderboardType = 1
	LeaderboardType_VOICE_TIME LeaderboardType = 2
	LeaderboardType_COMMANDS   LeaderboardType = 3
)

// Enum value maps for LeaderboardType.
var (
	LeaderboardType_name = map[int32]string{
		0: "MESSAGES",
		1: "REACTIONS",
		2: "VOICE_TIME",
		3: "COMMANDS",
	}
	LeaderboardType_value = map[string]int32{
		"MESSAGES":   0,
		"REACTIONS":  1,
		"VOICE_TIME": 2,
		"COMMANDS":   3,
	}
)

func (x LeaderboardType) Enum() *LeaderboardType {
	p := new(LeaderboardType)
	*p = x
	return p
}

func (x LeaderboardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderboardType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_roast_proto_enumTypes[1].Descriptor()
}

func (LeaderboardType) Type() protoreflect.EnumType {
	return &file_api_proto_roast_proto_enumTypes[1]
}

func (x LeaderboardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderboardType.Descriptor instead.
func (LeaderboardType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{1}
}

// Track activity
type ActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ActivityType           `protobuf:"varint,3,opt,name=type,proto3,enum=roast.ActivityType" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRequest) Reset() {
	*x = ActivityRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRequest) ProtoMessage() {}

func (x *ActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRequest.ProtoReflect.Descriptor instead.
func (*ActivityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivityRequest) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_MESSAGE
}

func (x *ActivityRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Generate roast
type RoastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoastRequest) Reset() {
	*x = RoastRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoastRequest) ProtoMessage() {}

func (x *RoastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoastRequest.ProtoReflect.Descriptor instead.
func (*RoastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{2}
}

func (x *RoastRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *RoastRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoastResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoastContent      string                 `protobuf:"bytes,2,opt,name=roast_content,json=roastContent,proto3" json:"roast_content,omitempty"`
	RoastCategory     string                 `protobuf:"bytes,3,opt,name=roast_category,json=roastCategory,proto3" json:"roast_category,omitempty"`
	CooldownRemaining int32                  `protobuf:"varint,4,opt,name=cooldown_remaining,json=cooldownRemaining,proto3" json:"cooldown_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoastResponse) Reset() {
	*x = RoastResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoastResponse) ProtoMessage() {}

func (x *RoastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoastResponse.ProtoReflect.Descriptor instead.
func (*RoastResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{3}
}

func (x *RoastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoastResponse) GetRoastContent() string {
	if x != nil {
		return x.RoastContent
	}
	return ""
}

func (x *RoastResponse) GetRoastCategory() string {
	if x != nil {
		return x.RoastCategory
	}
	return ""
}

func (x *RoastResponse) GetCooldownRemaining() int32 {
	if x != nil {
		return x.CooldownRemaining
	}
	return 0
}

// Get profile
type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Get leaderboard
type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Type          LeaderboardType        `protobuf:"varint,2,opt,name=type,proto3,enum=roast.LeaderboardType" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{6}
}

func (x *LeaderboardRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *LeaderboardRequest) GetType() LeaderboardType {
	if x != nil {
		return x.Type
	}
	return LeaderboardType_MESSAGES
}

func (x *LeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Get stats
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{8}
}

func (x *StatsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRoasts    int32                  `protobuf:"varint,1,opt,name=total_roasts,json=totalRoasts,proto3" json:"total_roasts,omitempty"`
	TotalUsers     int32                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	CategoryCounts map[string]int32       `protobuf:"bytes,3,rep,name=category_counts,json=categoryCounts,proto3" json:"category_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetTotalRoasts() int32 {
	if x != nil {
		return x.TotalRoasts
	}
	return 0
}

func (x *StatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *StatsResponse) GetCategoryCounts() map[string]int32 {
	if x != nil {
		return x.CategoryCounts
	}
	return nil
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_roast_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{10}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_roast_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	ReactionCount int32                  `protobuf:"varint,4,opt,name=reaction_count,json=reactionCount,proto3" json:"reaction_count,omitempty"`
	VoiceMinutes  int32                  `protobuf:"varint,5,opt,name=voice_minutes,json=voiceMinutes,proto3" json:"voice_minutes,omitempty"`
	CommandCount  int32                  `protobuf:"varint,6,opt,name=command_count,json=commandCount,proto3" json:"command_count,omitempty"`
	LastSeen      string                 `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_proto_roast_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{12}
}

func (x *UserProfile) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *UserProfile) GetReactionCount() int32 {
	if x != nil {
		return x.ReactionCount
	}
	return 0
}

func (x *UserProfile) GetVoiceMinutes() int32 {
	if x != nil {
		return x.VoiceMinutes
	}
	return 0
}

func (x *UserProfile) GetCommandCount() int32 {
	if x != nil {
		return x.CommandCount
	}
	return 0
}

func (x *UserProfile) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_api_proto_roast_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roast_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_roast_proto_rawDescGZIP(), []int{13}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_proto_roast_proto protoreflect.FileDescriptor

const file_api_proto_roast_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/roast.proto\x12\x05roast\"\x84\x01\n" +
	"\x0fActivityRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.roast.ActivityTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"F\n" +
	"\x10ActivityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\fRoastRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa4\x01\n" +
	"\rRoastResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rroast_content\x18\x02 \x01(\tR\froastContent\x12%\n" +
	"\x0eroast_category\x18\x03 \x01(\tR\rroastCategory\x12-\n" +
	"\x12cooldown_remaining\x18\x04 \x01(\x05R\x11cooldownRemaining\"D\n" +
	"\x0eProfileRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"?\n" +
	"\x0fProfileResponse\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.roast.UserProfileR\aprofile\"q\n" +
	"\x12LeaderboardRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.roast.LeaderboardTypeR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"H\n" +
	"\x13LeaderboardResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.roast.LeaderboardEntryR\aentries\")\n" +
	"\fStatsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"\xe9\x01\n" +
	"\rStatsResponse\x12!\n" +
	"\ftotal_roasts\x18\x01 \x01(\x05R\vtotalRoasts\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers\x12Q\n" +
	"\x0fcategory_counts\x18\x03 \x03(\v2(.roast.StatsResponse.CategoryCountsEntryR\x0ecategoryCounts\x1aA\n" +
	"\x13CategoryCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xf4\x01\n" +
	"\vUserProfile\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12%\n" +
	"\x0ereaction_count\x18\x04 \x01(\x05R\rreactionCount\x12#\n" +
	"\rvoice_minutes\x18\x05 \x01(\x05R\fvoiceMinutes\x12#\n" +
	"\rcommand_count\x18\x06 \x01(\x05R\fcommandCount\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\tR\blastSeen\"q\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value*A\n" +
	"\fActivityType\x12\v\n" +
	"\aMESSAGE\x10\x00\x12\f\n" +
	"\bREACTION\x10\x01\x12\t\n" +
	"\x05VOICE\x10\x02\x12\v\n" +
	"\aCOMMAND\x10\x03*L\n" +
	"\x0fLeaderboardType\x12\f\n" +
	"\bMESSAGES\x10\x00\x12\r\n" +
	"\tREACTIONS\x10\x01\x12\x0e\n" +
	"\n" +
	"VOICE_TIME\x10\x02\x12\f\n" +
	"\bCOMMANDS\x10\x032\x8f\x03\n" +
	"\fRoastService\x12@\n" +
	"\rTrackActivity\x12\x16.roast.ActivityRequest\x1a\x17.roast.ActivityResponse\x12:\n" +
	"\rGenerateRoast\x12\x13.roast.RoastRequest\x1a\x14.roast.RoastResponse\x12;\n" +
	"\n" +
	"GetProfile\x12\x15.roast.ProfileRequest\x1a\x16.roast.ProfileResponse\x12G\n" +
	"\x0eGetLeaderboard\x12\x19.roast.LeaderboardRequest\x1a\x1a.roast.LeaderboardResponse\x125\n" +
	"\bGetStats\x12\x13.roast.StatsRequest\x1a\x14.roast.StatsResponse\x12D\n" +
	"\vHealthCheck\x12\x19.roast.HealthCheckRequest\x1a\x1a.roast.HealthCheckResponseB-Z+github.com/nerufuyo/nerubot/api/proto/roastb\x06proto3"

var (
	file_api_proto_roast_proto_rawDescOnce sync.Once
	file_api_proto_roast_proto_rawDescData []byte
)

func file_api_proto_roast_proto_rawDescGZIP() []byte {
	file_api_proto_roast_proto_rawDescOnce.Do(func() {
		file_api_proto_roast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_roast_proto_rawDesc), len(file_api_proto_roast_proto_rawDesc)))
	})
	return file_api_proto_roast_proto_rawDescData
}

var file_api_proto_roast_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_roast_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_roast_proto_goTypes = []any{
	(ActivityType)(0),           // 0: roast.ActivityType
	(LeaderboardType)(0),        // 1: roast.LeaderboardType
	(*ActivityRequest)(nil),     // 2: roast.ActivityRequest
	(*ActivityResponse)(nil),    // 3: roast.ActivityResponse
	(*RoastRequest)(nil),        // 4: roast.RoastRequest
	(*RoastResponse)(nil),       // 5: roast.RoastResponse
	(*ProfileRequest)(nil),      // 6: roast.ProfileRequest
	(*ProfileResponse)(nil),     // 7: roast.ProfileResponse
	(*LeaderboardRequest)(nil),  // 8: roast.LeaderboardRequest
	(*LeaderboardResponse)(nil), // 9: roast.LeaderboardResponse
	(*StatsRequest)(nil),        // 10: roast.StatsRequest
	(*StatsResponse)(nil),       // 11: roast.StatsResponse
	(*HealthCheckRequest)(nil),  // 12: roast.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 13: roast.HealthCheckResponse
	(*UserProfile)(nil),         // 14: roast.UserProfile
	(*LeaderboardEntry)(nil),    // 15: roast.LeaderboardEntry
	nil,                         // 16: roast.StatsResponse.CategoryCountsEntry
}
var file_api_proto_roast_proto_depIdxs = []int32{
	0,  // 0: roast.ActivityRequest.type:type_name -> roast.ActivityType
	14, // 1: roast.ProfileResponse.profile:type_name -> roast.UserProfile
	1,  // 2: roast.LeaderboardRequest.type:type_name -> roast.LeaderboardType
	15, // 3: roast.LeaderboardResponse.entries:type_name -> roast.LeaderboardEntry
	16, // 4: roast.StatsResponse.category_counts:type_name -> roast.StatsResponse.CategoryCountsEntry
	2,  // 5: roast.RoastService.TrackActivity:input_type -> roast.ActivityRequest
	4,  // 6: roast.RoastService.GenerateRoast:input_type -> roast.RoastRequest
	6,  // 7: roast.RoastService.GetProfile:input_type -> roast.ProfileRequest
	8,  // 8: roast.RoastService.GetLeaderboard:input_type -> roast.LeaderboardRequest
	10, // 9: roast.RoastService.GetStats:input_type -> roast.StatsRequest
	12, // 10: roast.RoastService.HealthCheck:input_type -> roast.HealthCheckRequest
	3,  // 11: roast.RoastService.TrackActivity:output_type -> roast.ActivityResponse
	5,  // 12: roast.RoastService.GenerateRoast:output_type -> roast.RoastResponse
	7,  // 13: roast.RoastService.GetProfile:output_type -> roast.ProfileResponse
	9,  // 14: roast.RoastService.GetLeaderboard:output_type -> roast.LeaderboardResponse
	11, // 15: roast.RoastService.GetStats:output_type -> roast.StatsResponse
	13, // 16: roast.RoastService.HealthCheck:output_type -> roast.HealthCheckResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_roast_proto_init() }
func file_api_proto_roast_proto_init() {
	if File_api_proto_roast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_roast_proto_rawDesc), len(file_api_proto_roast_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_roast_proto_goTypes,
		DependencyIndexes: file_api_proto_roast_proto_depIdxs,
		EnumInfos:         file_api_proto_roast_proto_enumTypes,
		MessageInfos:      file_api_proto_roast_proto_msgTypes,
	}.Build()
	File_api_proto_roast_proto = out.File
	file_api_proto_roast_proto_goTypes = nil
	file_api_proto_roast_proto_depIdxs = nil
}
