// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/chatbot.proto

package chatbot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chat request
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_proto_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	ProviderUsed  string                 `protobuf:"bytes,3,opt,name=provider_used,json=providerUsed,proto3" json:"provider_used,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_api_proto_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetProviderUsed() string {
	if x != nil {
		return x.ProviderUsed
	}
	return ""
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

// Get session
type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_api_proto_chatbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_api_proto_chatbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Clear session
type ClearSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSessionRequest) Reset() {
	*x = ClearSessionRequest{}
	mi := &file_api_proto_chatbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSessionRequest) ProtoMessage() {}

func (x *ClearSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSessionRequest.ProtoReflect.Descriptor instead.
func (*ClearSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{4}
}

func (x *ClearSessionRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ClearSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSessionResponse) Reset() {
	*x = ClearSessionResponse{}
	mi := &file_api_proto_chatbot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSessionResponse) ProtoMessage() {}

func (x *ClearSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSessionResponse.ProtoReflect.Descriptor instead.
func (*ClearSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{5}
}

func (x *ClearSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get provider status
type ProviderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatusRequest) Reset() {
	*x = ProviderStatusRequest{}
	mi := &file_api_proto_chatbot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatusRequest) ProtoMessage() {}

func (x *ProviderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatusRequest.ProtoReflect.Descriptor instead.
func (*ProviderStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{6}
}

type ProviderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderStatus      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatusResponse) Reset() {
	*x = ProviderStatusResponse{}
	mi := &file_api_proto_chatbot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatusResponse) ProtoMessage() {}

func (x *ProviderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatusResponse.ProtoReflect.Descriptor instead.
func (*ProviderStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderStatusResponse) GetProviders() []*ProviderStatus {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_chatbot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_chatbot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GuildId         string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastInteraction string                 `protobuf:"bytes,5,opt,name=last_interaction,json=lastInteraction,proto3" json:"last_interaction,omitempty"`
	MessageCount    int32                  `protobuf:"varint,6,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_chatbot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Session) GetLastInteraction() string {
	if x != nil {
		return x.LastInteraction
	}
	return ""
}

func (x *Session) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_chatbot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Message) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProviderStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderName       string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Available          bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	TotalRequests      int32                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests int32                  `protobuf:"varint,4,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests     int32                  `protobuf:"varint,5,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	LastUsed           string                 `protobuf:"bytes,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_api_proto_chatbot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatbot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_chatbot_proto_rawDescGZIP(), []int{12}
}

func (x *ProviderStatus) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ProviderStatus) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ProviderStatus) GetSuccessfulRequests() int32 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *ProviderStatus) GetFailedRequests() int32 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *ProviderStatus) GetLastUsed() string {
	if x != nil {
		return x.LastUsed
	}
	return ""
}

var File_api_proto_chatbot_proto protoreflect.FileDescriptor

const file_api_proto_chatbot_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/chatbot.proto\x12\achatbot\"z\n" +
	"\vChatRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\"\x8a\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12#\n" +
	"\rprovider_used\x18\x03 \x01(\tR\fproviderUsed\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\"D\n" +
	"\x0eSessionRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"k\n" +
	"\x0fSessionResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.chatbot.SessionR\asession\x12,\n" +
	"\bmessages\x18\x02 \x03(\v2\x10.chatbot.MessageR\bmessages\"I\n" +
	"\x13ClearSessionRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x14ClearSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15ProviderStatusRequest\"O\n" +
	"\x16ProviderStatusResponse\x125\n" +
	"\tproviders\x18\x01 \x03(\v2\x17.chatbot.ProviderStatusR\tproviders\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xbc\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12)\n" +
	"\x10last_interaction\x18\x05 \x01(\tR\x0flastInteraction\x12#\n" +
	"\rmessage_count\x18\x06 \x01(\x05R\fmessageCount\"\xa3\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xf1\x01\n" +
	"\x0eProviderStatus\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x05R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x04 \x01(\x05R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x05 \x01(\x05R\x0efailedRequests\x12\x1b\n" +
	"\tlast_used\x18\x06 \x01(\tR\blastUsed2\xf3\x02\n" +
	"\x0eChatbotService\x123\n" +
	"\x04Chat\x12\x14.chatbot.ChatRequest\x1a\x15.chatbot.ChatResponse\x12?\n" +
	"\n" +
	"GetSession\x12\x17.chatbot.SessionRequest\x1a\x18.chatbot.SessionResponse\x12K\n" +
	"\fClearSession\x12\x1c.chatbot.ClearSessionRequest\x1a\x1d.chatbot.ClearSessionResponse\x12T\n" +
	"\x11GetProviderStatus\x12\x1e.chatbot.ProviderStatusRequest\x1a\x1f.chatbot.ProviderStatusResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.chatbot.HealthCheckRequest\x1a\x1c.chatbot.HealthCheckResponseB/Z-github.com/nerufuyo/nerubot/api/proto/chatbotb\x06proto3"

var (
	file_api_proto_chatbot_proto_rawDescOnce sync.Once
	file_api_proto_chatbot_proto_rawDescData []byte
)

func file_api_proto_chatbot_proto_rawDescGZIP() []byte {
	file_api_proto_chatbot_proto_rawDescOnce.Do(func() {
		file_api_proto_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chatbot_proto_rawDesc), len(file_api_proto_chatbot_proto_rawDesc)))
	})
	return file_api_proto_chatbot_proto_rawDescData
}

var file_api_proto_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_chatbot_proto_goTypes = []any{
	(*ChatRequest)(nil),            // 0: chatbot.ChatRequest
	(*ChatResponse)(nil),           // 1: chatbot.ChatResponse
	(*SessionRequest)(nil),         // 2: chatbot.SessionRequest
	(*SessionResponse)(nil),        // 3: chatbot.SessionResponse
	(*ClearSessionRequest)(nil),    // 4: chatbot.ClearSessionRequest
	(*ClearSessionResponse)(nil),   // 5: chatbot.ClearSessionResponse
	(*ProviderStatusRequest)(nil),  // 6: chatbot.ProviderStatusRequest
	(*ProviderStatusResponse)(nil), // 7: chatbot.ProviderStatusResponse
	(*HealthCheckRequest)(nil),     // 8: chatbot.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 9: chatbot.HealthCheckResponse
	(*Session)(nil),                // 10: chatbot.Session
	(*Message)(nil),                // 11: chatbot.Message
	(*ProviderStatus)(nil),         // 12: chatbot.ProviderStatus
}
var file_api_proto_chatbot_proto_depIdxs = []int32{
	10, // 0: chatbot.SessionResponse.session:type_name -> chatbot.Session
	11, // 1: chatbot.SessionResponse.messages:type_name -> chatbot.Message
	12, // 2: chatbot.ProviderStatusResponse.providers:type_name -> chatbot.ProviderStatus
	0,  // 3: chatbot.ChatbotService.Chat:input_type -> chatbot.ChatRequest
	2,  // 4: chatbot.ChatbotService.GetSession:input_type -> chatbot.SessionRequest
	4,  // 5: chatbot.ChatbotService.ClearSession:input_type -> chatbot.ClearSessionRequest
	6,  // 6: chatbot.ChatbotService.GetProviderStatus:input_type -> chatbot.ProviderStatusRequest
	8,  // 7: chatbot.ChatbotService.HealthCheck:input_type -> chatbot.HealthCheckRequest
	1,  // 8: chatbot.ChatbotService.Chat:output_type -> chatbot.ChatResponse
	3,  // 9: chatbot.ChatbotService.GetSession:output_type -> chatbot.SessionResponse
	5,  // 10: chatbot.ChatbotService.ClearSession:output_type -> chatbot.ClearSessionResponse
	7,  // 11: chatbot.ChatbotService.GetProviderStatus:output_type -> chatbot.ProviderStatusResponse
	9,  // 12: chatbot.ChatbotService.HealthCheck:output_type -> chatbot.HealthCheckResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_chatbot_proto_init() }
func file_api_proto_chatbot_proto_init() {
	if File_api_proto_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chatbot_proto_rawDesc), len(file_api_proto_chatbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chatbot_proto_goTypes,
		DependencyIndexes: file_api_proto_chatbot_proto_depIdxs,
		MessageInfos:      file_api_proto_chatbot_proto_msgTypes,
	}.Build()
	File_api_proto_chatbot_proto = out.File
	file_api_proto_chatbot_proto_goTypes = nil
	file_api_proto_chatbot_proto_depIdxs = nil
}
