// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/news.proto

package news

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fetch news
type FetchNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNewsRequest) Reset() {
	*x = FetchNewsRequest{}
	mi := &file_api_proto_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNewsRequest) ProtoMessage() {}

func (x *FetchNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNewsRequest.ProtoReflect.Descriptor instead.
func (*FetchNewsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{0}
}

func (x *FetchNewsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *FetchNewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FetchNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	TotalArticles int32                  `protobuf:"varint,2,opt,name=total_articles,json=totalArticles,proto3" json:"total_articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNewsResponse) Reset() {
	*x = FetchNewsResponse{}
	mi := &file_api_proto_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNewsResponse) ProtoMessage() {}

func (x *FetchNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNewsResponse.ProtoReflect.Descriptor instead.
func (*FetchNewsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{1}
}

func (x *FetchNewsResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *FetchNewsResponse) GetTotalArticles() int32 {
	if x != nil {
		return x.TotalArticles
	}
	return 0
}

// Add source
type AddSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	FeedType      string                 `protobuf:"bytes,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceRequest) Reset() {
	*x = AddSourceRequest{}
	mi := &file_api_proto_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceRequest) ProtoMessage() {}

func (x *AddSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceRequest.ProtoReflect.Descriptor instead.
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{2}
}

func (x *AddSourceRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *AddSourceRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *AddSourceRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *AddSourceRequest) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

type AddSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SourceId      int32                  `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceResponse) Reset() {
	*x = AddSourceResponse{}
	mi := &file_api_proto_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceResponse) ProtoMessage() {}

func (x *AddSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceResponse.ProtoReflect.Descriptor instead.
func (*AddSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{3}
}

func (x *AddSourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddSourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddSourceResponse) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

// Remove source
type RemoveSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	SourceId      int32                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceRequest) Reset() {
	*x = RemoveSourceRequest{}
	mi := &file_api_proto_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceRequest) ProtoMessage() {}

func (x *RemoveSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSourceRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *RemoveSourceRequest) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type RemoveSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceResponse) Reset() {
	*x = RemoveSourceResponse{}
	mi := &file_api_proto_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceResponse) ProtoMessage() {}

func (x *RemoveSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceResponse.ProtoReflect.Descriptor instead.
func (*RemoveSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveSourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get sources
type GetSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourcesRequest) Reset() {
	*x = GetSourcesRequest{}
	mi := &file_api_proto_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourcesRequest) ProtoMessage() {}

func (x *GetSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourcesRequest.ProtoReflect.Descriptor instead.
func (*GetSourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{6}
}

func (x *GetSourcesRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourcesResponse) Reset() {
	*x = GetSourcesResponse{}
	mi := &file_api_proto_news_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourcesResponse) ProtoMessage() {}

func (x *GetSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourcesResponse.ProtoReflect.Descriptor instead.
func (*GetSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{7}
}

func (x *GetSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Publish news
type PublishNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ArticleId     int32                  `protobuf:"varint,3,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNewsRequest) Reset() {
	*x = PublishNewsRequest{}
	mi := &file_api_proto_news_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNewsRequest) ProtoMessage() {}

func (x *PublishNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNewsRequest.ProtoReflect.Descriptor instead.
func (*PublishNewsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{8}
}

func (x *PublishNewsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *PublishNewsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PublishNewsRequest) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type PublishNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNewsResponse) Reset() {
	*x = PublishNewsResponse{}
	mi := &file_api_proto_news_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNewsResponse) ProtoMessage() {}

func (x *PublishNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNewsResponse.ProtoReflect.Descriptor instead.
func (*PublishNewsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{9}
}

func (x *PublishNewsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishNewsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishNewsResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_news_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{10}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_news_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	SourceName    string                 `protobuf:"bytes,6,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_api_proto_news_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{12}
}

func (x *Article) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Article) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GuildId       string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	SourceName    string                 `protobuf:"bytes,3,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	FeedType      string                 `protobuf:"bytes,5,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastFetched   string                 `protobuf:"bytes,7,opt,name=last_fetched,json=lastFetched,proto3" json:"last_fetched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_api_proto_news_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_news_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_api_proto_news_proto_rawDescGZIP(), []int{13}
}

func (x *Source) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Source) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Source) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Source) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Source) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *Source) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Source) GetLastFetched() string {
	if x != nil {
		return x.LastFetched
	}
	return ""
}

var File_api_proto_news_proto protoreflect.FileDescriptor

const file_api_proto_news_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/news.proto\x12\x04news\"C\n" +
	"\x10FetchNewsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"e\n" +
	"\x11FetchNewsResponse\x12)\n" +
	"\barticles\x18\x01 \x03(\v2\r.news.ArticleR\barticles\x12%\n" +
	"\x0etotal_articles\x18\x02 \x01(\x05R\rtotalArticles\"\x8a\x01\n" +
	"\x10AddSourceRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\tR\bfeedType\"d\n" +
	"\x11AddSourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\x05R\bsourceId\"M\n" +
	"\x13RemoveSourceRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x05R\bsourceId\"J\n" +
	"\x14RemoveSourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x11GetSourcesRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"<\n" +
	"\x12GetSourcesResponse\x12&\n" +
	"\asources\x18\x01 \x03(\v2\f.news.SourceR\asources\"m\n" +
	"\x12PublishNewsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x03 \x01(\x05R\tarticleId\"h\n" +
	"\x13PublishNewsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x9f\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\fpublished_at\x18\x05 \x01(\tR\vpublishedAt\x12\x1f\n" +
	"\vsource_name\x18\x06 \x01(\tR\n" +
	"sourceName\"\xcd\x01\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12\x1f\n" +
	"\vsource_name\x18\x03 \x01(\tR\n" +
	"sourceName\x12\x1d\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tR\tsourceUrl\x12\x1b\n" +
	"\tfeed_type\x18\x05 \x01(\tR\bfeedType\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12!\n" +
	"\flast_fetched\x18\a \x01(\tR\vlastFetched2\x99\x03\n" +
	"\vNewsService\x12<\n" +
	"\tFetchNews\x12\x16.news.FetchNewsRequest\x1a\x17.news.FetchNewsResponse\x12<\n" +
	"\tAddSource\x12\x16.news.AddSourceRequest\x1a\x17.news.AddSourceResponse\x12E\n" +
	"\fRemoveSource\x12\x19.news.RemoveSourceRequest\x1a\x1a.news.RemoveSourceResponse\x12?\n" +
	"\n" +
	"GetSources\x12\x17.news.GetSourcesRequest\x1a\x18.news.GetSourcesResponse\x12B\n" +
	"\vPublishNews\x12\x18.news.PublishNewsRequest\x1a\x19.news.PublishNewsResponse\x12B\n" +
	"\vHealthCheck\x12\x18.news.HealthCheckRequest\x1a\x19.news.HealthCheckResponseB,Z*github.com/nerufuyo/nerubot/api/proto/newsb\x06proto3"

var (
	file_api_proto_news_proto_rawDescOnce sync.Once
	file_api_proto_news_proto_rawDescData []byte
)

func file_api_proto_news_proto_rawDescGZIP() []byte {
	file_api_proto_news_proto_rawDescOnce.Do(func() {
		file_api_proto_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_news_proto_rawDesc), len(file_api_proto_news_proto_rawDesc)))
	})
	return file_api_proto_news_proto_rawDescData
}

var file_api_proto_news_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_news_proto_goTypes = []any{
	(*FetchNewsRequest)(nil),     // 0: news.FetchNewsRequest
	(*FetchNewsResponse)(nil),    // 1: news.FetchNewsResponse
	(*AddSourceRequest)(nil),     // 2: news.AddSourceRequest
	(*AddSourceResponse)(nil),    // 3: news.AddSourceResponse
	(*RemoveSourceRequest)(nil),  // 4: news.RemoveSourceRequest
	(*RemoveSourceResponse)(nil), // 5: news.RemoveSourceResponse
	(*GetSourcesRequest)(nil),    // 6: news.GetSourcesRequest
	(*GetSourcesResponse)(nil),   // 7: news.GetSourcesResponse
	(*PublishNewsRequest)(nil),   // 8: news.PublishNewsRequest
	(*PublishNewsResponse)(nil),  // 9: news.PublishNewsResponse
	(*HealthCheckRequest)(nil),   // 10: news.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 11: news.HealthCheckResponse
	(*Article)(nil),              // 12: news.Article
	(*Source)(nil),               // 13: news.Source
}
var file_api_proto_news_proto_depIdxs = []int32{
	12, // 0: news.FetchNewsResponse.articles:type_name -> news.Article
	13, // 1: news.GetSourcesResponse.sources:type_name -> news.Source
	0,  // 2: news.NewsService.FetchNews:input_type -> news.FetchNewsRequest
	2,  // 3: news.NewsService.AddSource:input_type -> news.AddSourceRequest
	4,  // 4: news.NewsService.RemoveSource:input_type -> news.RemoveSourceRequest
	6,  // 5: news.NewsService.GetSources:input_type -> news.GetSourcesRequest
	8,  // 6: news.NewsService.PublishNews:input_type -> news.PublishNewsRequest
	10, // 7: news.NewsService.HealthCheck:input_type -> news.HealthCheckRequest
	1,  // 8: news.NewsService.FetchNews:output_type -> news.FetchNewsResponse
	3,  // 9: news.NewsService.AddSource:output_type -> news.AddSourceResponse
	5,  // 10: news.NewsService.RemoveSource:output_type -> news.RemoveSourceResponse
	7,  // 11: news.NewsService.GetSources:output_type -> news.GetSourcesResponse
	9,  // 12: news.NewsService.PublishNews:output_type -> news.PublishNewsResponse
	11, // 13: news.NewsService.HealthCheck:output_type -> news.HealthCheckResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_news_proto_init() }
func file_api_proto_news_proto_init() {
	if File_api_proto_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_news_proto_rawDesc), len(file_api_proto_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_news_proto_goTypes,
		DependencyIndexes: file_api_proto_news_proto_depIdxs,
		MessageInfos:      file_api_proto_news_proto_msgTypes,
	}.Build()
	File_api_proto_news_proto = out.File
	file_api_proto_news_proto_goTypes = nil
	file_api_proto_news_proto_depIdxs = nil
}
