// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/whale.proto

package whale

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhaleService_GetTransactions_FullMethodName     = "/whale.WhaleService/GetTransactions"
	WhaleService_GetAlertSettings_FullMethodName    = "/whale.WhaleService/GetAlertSettings"
	WhaleService_UpdateAlertSettings_FullMethodName = "/whale.WhaleService/UpdateAlertSettings"
	WhaleService_HealthCheck_FullMethodName         = "/whale.WhaleService/HealthCheck"
)

// WhaleServiceClient is the client API for WhaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Whale service definition
type WhaleServiceClient interface {
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
	GetAlertSettings(ctx context.Context, in *GetAlertSettingsRequest, opts ...grpc.CallOption) (*GetAlertSettingsResponse, error)
	UpdateAlertSettings(ctx context.Context, in *UpdateAlertSettingsRequest, opts ...grpc.CallOption) (*UpdateAlertSettingsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type whaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhaleServiceClient(cc grpc.ClientConnInterface) WhaleServiceClient {
	return &whaleServiceClient{cc}
}

func (c *whaleServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, WhaleService_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whaleServiceClient) GetAlertSettings(ctx context.Context, in *GetAlertSettingsRequest, opts ...grpc.CallOption) (*GetAlertSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertSettingsResponse)
	err := c.cc.Invoke(ctx, WhaleService_GetAlertSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whaleServiceClient) UpdateAlertSettings(ctx context.Context, in *UpdateAlertSettingsRequest, opts ...grpc.CallOption) (*UpdateAlertSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAlertSettingsResponse)
	err := c.cc.Invoke(ctx, WhaleService_UpdateAlertSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whaleServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WhaleService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhaleServiceServer is the server API for WhaleService service.
// All implementations must embed UnimplementedWhaleServiceServer
// for forward compatibility.
//
// Whale service definition
type WhaleServiceServer interface {
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	GetAlertSettings(context.Context, *GetAlertSettingsRequest) (*GetAlertSettingsResponse, error)
	UpdateAlertSettings(context.Context, *UpdateAlertSettingsRequest) (*UpdateAlertSettingsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedWhaleServiceServer()
}

// UnimplementedWhaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhaleServiceServer struct{}

func (UnimplementedWhaleServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedWhaleServiceServer) GetAlertSettings(context.Context, *GetAlertSettingsRequest) (*GetAlertSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertSettings not implemented")
}
func (UnimplementedWhaleServiceServer) UpdateAlertSettings(context.Context, *UpdateAlertSettingsRequest) (*UpdateAlertSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAlertSettings not implemented")
}
func (UnimplementedWhaleServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWhaleServiceServer) mustEmbedUnimplementedWhaleServiceServer() {}
func (UnimplementedWhaleServiceServer) testEmbeddedByValue()                      {}

// UnsafeWhaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhaleServiceServer will
// result in compilation errors.
type UnsafeWhaleServiceServer interface {
	mustEmbedUnimplementedWhaleServiceServer()
}

func RegisterWhaleServiceServer(s grpc.ServiceRegistrar, srv WhaleServiceServer) {
	// If the following call panics, it indicates UnimplementedWhaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhaleService_ServiceDesc, srv)
}

func _WhaleService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhaleServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhaleService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhaleServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhaleService_GetAlertSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhaleServiceServer).GetAlertSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhaleService_GetAlertSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhaleServiceServer).GetAlertSettings(ctx, req.(*GetAlertSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhaleService_UpdateAlertSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhaleServiceServer).UpdateAlertSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhaleService_UpdateAlertSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhaleServiceServer).UpdateAlertSettings(ctx, req.(*UpdateAlertSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhaleService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhaleServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhaleService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhaleServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhaleService_ServiceDesc is the grpc.ServiceDesc for WhaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whale.WhaleService",
	HandlerType: (*WhaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _WhaleService_GetTransactions_Handler,
		},
		{
			MethodName: "GetAlertSettings",
			Handler:    _WhaleService_GetAlertSettings_Handler,
		},
		{
			MethodName: "UpdateAlertSettings",
			Handler:    _WhaleService_UpdateAlertSettings_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WhaleService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/whale.proto",
}
