// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/music.proto

package music

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Play Request
type PlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	SongUrl       string                 `protobuf:"bytes,2,opt,name=song_url,json=songUrl,proto3" json:"song_url,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,3,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	mi := &file_api_proto_music_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{0}
}

func (x *PlayRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *PlayRequest) GetSongUrl() string {
	if x != nil {
		return x.SongUrl
	}
	return ""
}

func (x *PlayRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *PlayRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type PlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Song          *Song                  `protobuf:"bytes,3,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	mi := &file_api_proto_music_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{1}
}

func (x *PlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlayResponse) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

// Pause Request
type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_api_proto_music_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{2}
}

func (x *PauseRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_api_proto_music_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{3}
}

func (x *PauseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Resume Request
type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_api_proto_music_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_api_proto_music_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Skip Request
type SkipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipRequest) Reset() {
	*x = SkipRequest{}
	mi := &file_api_proto_music_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipRequest) ProtoMessage() {}

func (x *SkipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipRequest.ProtoReflect.Descriptor instead.
func (*SkipRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{6}
}

func (x *SkipRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type SkipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextSong      *Song                  `protobuf:"bytes,3,opt,name=next_song,json=nextSong,proto3" json:"next_song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipResponse) Reset() {
	*x = SkipResponse{}
	mi := &file_api_proto_music_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipResponse) ProtoMessage() {}

func (x *SkipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipResponse.ProtoReflect.Descriptor instead.
func (*SkipResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{7}
}

func (x *SkipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SkipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SkipResponse) GetNextSong() *Song {
	if x != nil {
		return x.NextSong
	}
	return nil
}

// Stop Request
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_music_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{8}
}

func (x *StopRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_music_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{9}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Queue Request
type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	SongUrl       string                 `protobuf:"bytes,2,opt,name=song_url,json=songUrl,proto3" json:"song_url,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,3,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_api_proto_music_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{10}
}

func (x *QueueRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *QueueRequest) GetSongUrl() string {
	if x != nil {
		return x.SongUrl
	}
	return ""
}

func (x *QueueRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type QueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResponse) Reset() {
	*x = QueueResponse{}
	mi := &file_api_proto_music_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResponse) ProtoMessage() {}

func (x *QueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResponse.ProtoReflect.Descriptor instead.
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{11}
}

func (x *QueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueueResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Now Playing Request
type NowPlayingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowPlayingRequest) Reset() {
	*x = NowPlayingRequest{}
	mi := &file_api_proto_music_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowPlayingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowPlayingRequest) ProtoMessage() {}

func (x *NowPlayingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowPlayingRequest.ProtoReflect.Descriptor instead.
func (*NowPlayingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{12}
}

func (x *NowPlayingRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type NowPlayingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPlaying     bool                   `protobuf:"varint,1,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	CurrentSong   *Song                  `protobuf:"bytes,2,opt,name=current_song,json=currentSong,proto3" json:"current_song,omitempty"`
	LoopMode      string                 `protobuf:"bytes,3,opt,name=loop_mode,json=loopMode,proto3" json:"loop_mode,omitempty"`
	Volume        int32                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowPlayingResponse) Reset() {
	*x = NowPlayingResponse{}
	mi := &file_api_proto_music_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowPlayingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowPlayingResponse) ProtoMessage() {}

func (x *NowPlayingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowPlayingResponse.ProtoReflect.Descriptor instead.
func (*NowPlayingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{13}
}

func (x *NowPlayingResponse) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *NowPlayingResponse) GetCurrentSong() *Song {
	if x != nil {
		return x.CurrentSong
	}
	return nil
}

func (x *NowPlayingResponse) GetLoopMode() string {
	if x != nil {
		return x.LoopMode
	}
	return ""
}

func (x *NowPlayingResponse) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// Get Queue Request
type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_api_proto_music_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{14}
}

func (x *GetQueueRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	TotalSongs    int32                  `protobuf:"varint,2,opt,name=total_songs,json=totalSongs,proto3" json:"total_songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_api_proto_music_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{15}
}

func (x *GetQueueResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *GetQueueResponse) GetTotalSongs() int32 {
	if x != nil {
		return x.TotalSongs
	}
	return 0
}

// Set Loop Request
type SetLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	LoopMode      string                 `protobuf:"bytes,2,opt,name=loop_mode,json=loopMode,proto3" json:"loop_mode,omitempty"` // "none", "single", "queue"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoopRequest) Reset() {
	*x = SetLoopRequest{}
	mi := &file_api_proto_music_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoopRequest) ProtoMessage() {}

func (x *SetLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoopRequest.ProtoReflect.Descriptor instead.
func (*SetLoopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{16}
}

func (x *SetLoopRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SetLoopRequest) GetLoopMode() string {
	if x != nil {
		return x.LoopMode
	}
	return ""
}

type SetLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LoopMode      string                 `protobuf:"bytes,3,opt,name=loop_mode,json=loopMode,proto3" json:"loop_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoopResponse) Reset() {
	*x = SetLoopResponse{}
	mi := &file_api_proto_music_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoopResponse) ProtoMessage() {}

func (x *SetLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoopResponse.ProtoReflect.Descriptor instead.
func (*SetLoopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{17}
}

func (x *SetLoopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetLoopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetLoopResponse) GetLoopMode() string {
	if x != nil {
		return x.LoopMode
	}
	return ""
}

// Set Volume Request
type SetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Volume        int32                  `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVolumeRequest) Reset() {
	*x = SetVolumeRequest{}
	mi := &file_api_proto_music_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeRequest) ProtoMessage() {}

func (x *SetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeRequest.ProtoReflect.Descriptor instead.
func (*SetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{18}
}

func (x *SetVolumeRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SetVolumeRequest) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type SetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Volume        int32                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVolumeResponse) Reset() {
	*x = SetVolumeResponse{}
	mi := &file_api_proto_music_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeResponse) ProtoMessage() {}

func (x *SetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeResponse.ProtoReflect.Descriptor instead.
func (*SetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{19}
}

func (x *SetVolumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetVolumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetVolumeResponse) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_music_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{20}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_music_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	AddedAt       string                 `protobuf:"bytes,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_api_proto_music_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_music_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_api_proto_music_proto_rawDescGZIP(), []int{22}
}

func (x *Song) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Song) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *Song) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

func (x *Song) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Song) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

var File_api_proto_music_proto protoreflect.FileDescriptor

const file_api_proto_music_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/music.proto\x12\x05music\"\x85\x01\n" +
	"\vPlayRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x19\n" +
	"\bsong_url\x18\x02 \x01(\tR\asongUrl\x12!\n" +
	"\frequested_by\x18\x03 \x01(\tR\vrequestedBy\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\"c\n" +
	"\fPlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x04song\x18\x03 \x01(\v2\v.music.SongR\x04song\")\n" +
	"\fPauseRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"C\n" +
	"\rPauseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\rResumeRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"D\n" +
	"\x0eResumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\vSkipRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"l\n" +
	"\fSkipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\tnext_song\x18\x03 \x01(\v2\v.music.SongR\bnextSong\"(\n" +
	"\vStopRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\fQueueRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x19\n" +
	"\bsong_url\x18\x02 \x01(\tR\asongUrl\x12!\n" +
	"\frequested_by\x18\x03 \x01(\tR\vrequestedBy\"_\n" +
	"\rQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\".\n" +
	"\x11NowPlayingRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"\x98\x01\n" +
	"\x12NowPlayingResponse\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x01 \x01(\bR\tisPlaying\x12.\n" +
	"\fcurrent_song\x18\x02 \x01(\v2\v.music.SongR\vcurrentSong\x12\x1b\n" +
	"\tloop_mode\x18\x03 \x01(\tR\bloopMode\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x05R\x06volume\",\n" +
	"\x0fGetQueueRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"V\n" +
	"\x10GetQueueResponse\x12!\n" +
	"\x05songs\x18\x01 \x03(\v2\v.music.SongR\x05songs\x12\x1f\n" +
	"\vtotal_songs\x18\x02 \x01(\x05R\n" +
	"totalSongs\"H\n" +
	"\x0eSetLoopRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1b\n" +
	"\tloop_mode\x18\x02 \x01(\tR\bloopMode\"b\n" +
	"\x0fSetLoopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tloop_mode\x18\x03 \x01(\tR\bloopMode\"E\n" +
	"\x10SetVolumeRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x05R\x06volume\"_\n" +
	"\x11SetVolumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x05R\x06volume\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb6\x01\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\x12\x19\n" +
	"\badded_at\x18\x05 \x01(\tR\aaddedAt\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail2\x80\x05\n" +
	"\fMusicService\x12/\n" +
	"\x04Play\x12\x12.music.PlayRequest\x1a\x13.music.PlayResponse\x122\n" +
	"\x05Pause\x12\x13.music.PauseRequest\x1a\x14.music.PauseResponse\x125\n" +
	"\x06Resume\x12\x14.music.ResumeRequest\x1a\x15.music.ResumeResponse\x12/\n" +
	"\x04Skip\x12\x12.music.SkipRequest\x1a\x13.music.SkipResponse\x12/\n" +
	"\x04Stop\x12\x12.music.StopRequest\x1a\x13.music.StopResponse\x122\n" +
	"\x05Queue\x12\x13.music.QueueRequest\x1a\x14.music.QueueResponse\x12A\n" +
	"\n" +
	"NowPlaying\x12\x18.music.NowPlayingRequest\x1a\x19.music.NowPlayingResponse\x12;\n" +
	"\bGetQueue\x12\x16.music.GetQueueRequest\x1a\x17.music.GetQueueResponse\x128\n" +
	"\aSetLoop\x12\x15.music.SetLoopRequest\x1a\x16.music.SetLoopResponse\x12>\n" +
	"\tSetVolume\x12\x17.music.SetVolumeRequest\x1a\x18.music.SetVolumeResponse\x12D\n" +
	"\vHealthCheck\x12\x19.music.HealthCheckRequest\x1a\x1a.music.HealthCheckResponseB-Z+github.com/nerufuyo/nerubot/api/proto/musicb\x06proto3"

var (
	file_api_proto_music_proto_rawDescOnce sync.Once
	file_api_proto_music_proto_rawDescData []byte
)

func file_api_proto_music_proto_rawDescGZIP() []byte {
	file_api_proto_music_proto_rawDescOnce.Do(func() {
		file_api_proto_music_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_music_proto_rawDesc), len(file_api_proto_music_proto_rawDesc)))
	})
	return file_api_proto_music_proto_rawDescData
}

var file_api_proto_music_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_music_proto_goTypes = []any{
	(*PlayRequest)(nil),         // 0: music.PlayRequest
	(*PlayResponse)(nil),        // 1: music.PlayResponse
	(*PauseRequest)(nil),        // 2: music.PauseRequest
	(*PauseResponse)(nil),       // 3: music.PauseResponse
	(*ResumeRequest)(nil),       // 4: music.ResumeRequest
	(*ResumeResponse)(nil),      // 5: music.ResumeResponse
	(*SkipRequest)(nil),         // 6: music.SkipRequest
	(*SkipResponse)(nil),        // 7: music.SkipResponse
	(*StopRequest)(nil),         // 8: music.StopRequest
	(*StopResponse)(nil),        // 9: music.StopResponse
	(*QueueRequest)(nil),        // 10: music.QueueRequest
	(*QueueResponse)(nil),       // 11: music.QueueResponse
	(*NowPlayingRequest)(nil),   // 12: music.NowPlayingRequest
	(*NowPlayingResponse)(nil),  // 13: music.NowPlayingResponse
	(*GetQueueRequest)(nil),     // 14: music.GetQueueRequest
	(*GetQueueResponse)(nil),    // 15: music.GetQueueResponse
	(*SetLoopRequest)(nil),      // 16: music.SetLoopRequest
	(*SetLoopResponse)(nil),     // 17: music.SetLoopResponse
	(*SetVolumeRequest)(nil),    // 18: music.SetVolumeRequest
	(*SetVolumeResponse)(nil),   // 19: music.SetVolumeResponse
	(*HealthCheckRequest)(nil),  // 20: music.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 21: music.HealthCheckResponse
	(*Song)(nil),                // 22: music.Song
}
var file_api_proto_music_proto_depIdxs = []int32{
	22, // 0: music.PlayResponse.song:type_name -> music.Song
	22, // 1: music.SkipResponse.next_song:type_name -> music.Song
	22, // 2: music.NowPlayingResponse.current_song:type_name -> music.Song
	22, // 3: music.GetQueueResponse.songs:type_name -> music.Song
	0,  // 4: music.MusicService.Play:input_type -> music.PlayRequest
	2,  // 5: music.MusicService.Pause:input_type -> music.PauseRequest
	4,  // 6: music.MusicService.Resume:input_type -> music.ResumeRequest
	6,  // 7: music.MusicService.Skip:input_type -> music.SkipRequest
	8,  // 8: music.MusicService.Stop:input_type -> music.StopRequest
	10, // 9: music.MusicService.Queue:input_type -> music.QueueRequest
	12, // 10: music.MusicService.NowPlaying:input_type -> music.NowPlayingRequest
	14, // 11: music.MusicService.GetQueue:input_type -> music.GetQueueRequest
	16, // 12: music.MusicService.SetLoop:input_type -> music.SetLoopRequest
	18, // 13: music.MusicService.SetVolume:input_type -> music.SetVolumeRequest
	20, // 14: music.MusicService.HealthCheck:input_type -> music.HealthCheckRequest
	1,  // 15: music.MusicService.Play:output_type -> music.PlayResponse
	3,  // 16: music.MusicService.Pause:output_type -> music.PauseResponse
	5,  // 17: music.MusicService.Resume:output_type -> music.ResumeResponse
	7,  // 18: music.MusicService.Skip:output_type -> music.SkipResponse
	9,  // 19: music.MusicService.Stop:output_type -> music.StopResponse
	11, // 20: music.MusicService.Queue:output_type -> music.QueueResponse
	13, // 21: music.MusicService.NowPlaying:output_type -> music.NowPlayingResponse
	15, // 22: music.MusicService.GetQueue:output_type -> music.GetQueueResponse
	17, // 23: music.MusicService.SetLoop:output_type -> music.SetLoopResponse
	19, // 24: music.MusicService.SetVolume:output_type -> music.SetVolumeResponse
	21, // 25: music.MusicService.HealthCheck:output_type -> music.HealthCheckResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_music_proto_init() }
func file_api_proto_music_proto_init() {
	if File_api_proto_music_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_music_proto_rawDesc), len(file_api_proto_music_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_music_proto_goTypes,
		DependencyIndexes: file_api_proto_music_proto_depIdxs,
		MessageInfos:      file_api_proto_music_proto_msgTypes,
	}.Build()
	File_api_proto_music_proto = out.File
	file_api_proto_music_proto_goTypes = nil
	file_api_proto_music_proto_depIdxs = nil
}
