// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/whale.proto

package whale

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get transactions
type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Blockchain    string                 `protobuf:"bytes,3,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_api_proto_whale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *GetTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsRequest) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

type GetTransactionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Transactions      []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,2,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_api_proto_whale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

// Get alert settings
type GetAlertSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertSettingsRequest) Reset() {
	*x = GetAlertSettingsRequest{}
	mi := &file_api_proto_whale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertSettingsRequest) ProtoMessage() {}

func (x *GetAlertSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertSettingsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type GetAlertSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *AlertSettings         `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertSettingsResponse) Reset() {
	*x = GetAlertSettingsResponse{}
	mi := &file_api_proto_whale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertSettingsResponse) ProtoMessage() {}

func (x *GetAlertSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertSettingsResponse) GetSettings() *AlertSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Update alert settings
type UpdateAlertSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Settings      *AlertSettings         `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertSettingsRequest) Reset() {
	*x = UpdateAlertSettingsRequest{}
	mi := &file_api_proto_whale_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertSettingsRequest) ProtoMessage() {}

func (x *UpdateAlertSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlertSettingsRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *UpdateAlertSettingsRequest) GetSettings() *AlertSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateAlertSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Settings      *AlertSettings         `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertSettingsResponse) Reset() {
	*x = UpdateAlertSettingsResponse{}
	mi := &file_api_proto_whale_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertSettingsResponse) ProtoMessage() {}

func (x *UpdateAlertSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAlertSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAlertSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAlertSettingsResponse) GetSettings() *AlertSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_whale_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_whale_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Common message types
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Blockchain      string                 `protobuf:"bytes,2,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	TransactionHash string                 `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountUsd       float64                `protobuf:"fixed64,5,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	FromAddress     string                 `protobuf:"bytes,6,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress       string                 `protobuf:"bytes,7,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Timestamp       string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_whale_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{8}
}

func (x *Transaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *Transaction) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetAmountUsd() float64 {
	if x != nil {
		return x.AmountUsd
	}
	return 0
}

func (x *Transaction) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *Transaction) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *Transaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AlertSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MinAmountUsd  float64                `protobuf:"fixed64,3,opt,name=min_amount_usd,json=minAmountUsd,proto3" json:"min_amount_usd,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Blockchains   []string               `protobuf:"bytes,5,rep,name=blockchains,proto3" json:"blockchains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertSettings) Reset() {
	*x = AlertSettings{}
	mi := &file_api_proto_whale_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertSettings) ProtoMessage() {}

func (x *AlertSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whale_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertSettings.ProtoReflect.Descriptor instead.
func (*AlertSettings) Descriptor() ([]byte, []int) {
	return file_api_proto_whale_proto_rawDescGZIP(), []int{9}
}

func (x *AlertSettings) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *AlertSettings) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AlertSettings) GetMinAmountUsd() float64 {
	if x != nil {
		return x.MinAmountUsd
	}
	return 0
}

func (x *AlertSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertSettings) GetBlockchains() []string {
	if x != nil {
		return x.Blockchains
	}
	return nil
}

var File_api_proto_whale_proto protoreflect.FileDescriptor

const file_api_proto_whale_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/whale.proto\x12\x05whale\"i\n" +
	"\x16GetTransactionsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x03 \x01(\tR\n" +
	"blockchain\"\x80\x01\n" +
	"\x17GetTransactionsResponse\x126\n" +
	"\ftransactions\x18\x01 \x03(\v2\x12.whale.TransactionR\ftransactions\x12-\n" +
	"\x12total_transactions\x18\x02 \x01(\x05R\x11totalTransactions\"4\n" +
	"\x17GetAlertSettingsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"L\n" +
	"\x18GetAlertSettingsResponse\x120\n" +
	"\bsettings\x18\x01 \x01(\v2\x14.whale.AlertSettingsR\bsettings\"i\n" +
	"\x1aUpdateAlertSettingsRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x120\n" +
	"\bsettings\x18\x02 \x01(\v2\x14.whale.AlertSettingsR\bsettings\"\x83\x01\n" +
	"\x1bUpdateAlertSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bsettings\x18\x03 \x01(\v2\x14.whale.AlertSettingsR\bsettings\"\x14\n" +
	"\x12HealthCheckRequest\"c\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xff\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x02 \x01(\tR\n" +
	"blockchain\x12)\n" +
	"\x10transaction_hash\x18\x03 \x01(\tR\x0ftransactionHash\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x05 \x01(\x01R\tamountUsd\x12!\n" +
	"\ffrom_address\x18\x06 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\a \x01(\tR\ttoAddress\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\"\xab\x01\n" +
	"\rAlertSettings\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12$\n" +
	"\x0emin_amount_usd\x18\x03 \x01(\x01R\fminAmountUsd\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12 \n" +
	"\vblockchains\x18\x05 \x03(\tR\vblockchains2\xd9\x02\n" +
	"\fWhaleService\x12P\n" +
	"\x0fGetTransactions\x12\x1d.whale.GetTransactionsRequest\x1a\x1e.whale.GetTransactionsResponse\x12S\n" +
	"\x10GetAlertSettings\x12\x1e.whale.GetAlertSettingsRequest\x1a\x1f.whale.GetAlertSettingsResponse\x12\\\n" +
	"\x13UpdateAlertSettings\x12!.whale.UpdateAlertSettingsRequest\x1a\".whale.UpdateAlertSettingsResponse\x12D\n" +
	"\vHealthCheck\x12\x19.whale.HealthCheckRequest\x1a\x1a.whale.HealthCheckResponseB-Z+github.com/nerufuyo/nerubot/api/proto/whaleb\x06proto3"

var (
	file_api_proto_whale_proto_rawDescOnce sync.Once
	file_api_proto_whale_proto_rawDescData []byte
)

func file_api_proto_whale_proto_rawDescGZIP() []byte {
	file_api_proto_whale_proto_rawDescOnce.Do(func() {
		file_api_proto_whale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_whale_proto_rawDesc), len(file_api_proto_whale_proto_rawDesc)))
	})
	return file_api_proto_whale_proto_rawDescData
}

var file_api_proto_whale_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_whale_proto_goTypes = []any{
	(*GetTransactionsRequest)(nil),      // 0: whale.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),     // 1: whale.GetTransactionsResponse
	(*GetAlertSettingsRequest)(nil),     // 2: whale.GetAlertSettingsRequest
	(*GetAlertSettingsResponse)(nil),    // 3: whale.GetAlertSettingsResponse
	(*UpdateAlertSettingsRequest)(nil),  // 4: whale.UpdateAlertSettingsRequest
	(*UpdateAlertSettingsResponse)(nil), // 5: whale.UpdateAlertSettingsResponse
	(*HealthCheckRequest)(nil),          // 6: whale.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 7: whale.HealthCheckResponse
	(*Transaction)(nil),                 // 8: whale.Transaction
	(*AlertSettings)(nil),               // 9: whale.AlertSettings
}
var file_api_proto_whale_proto_depIdxs = []int32{
	8, // 0: whale.GetTransactionsResponse.transactions:type_name -> whale.Transaction
	9, // 1: whale.GetAlertSettingsResponse.settings:type_name -> whale.AlertSettings
	9, // 2: whale.UpdateAlertSettingsRequest.settings:type_name -> whale.AlertSettings
	9, // 3: whale.UpdateAlertSettingsResponse.settings:type_name -> whale.AlertSettings
	0, // 4: whale.WhaleService.GetTransactions:input_type -> whale.GetTransactionsRequest
	2, // 5: whale.WhaleService.GetAlertSettings:input_type -> whale.GetAlertSettingsRequest
	4, // 6: whale.WhaleService.UpdateAlertSettings:input_type -> whale.UpdateAlertSettingsRequest
	6, // 7: whale.WhaleService.HealthCheck:input_type -> whale.HealthCheckRequest
	1, // 8: whale.WhaleService.GetTransactions:output_type -> whale.GetTransactionsResponse
	3, // 9: whale.WhaleService.GetAlertSettings:output_type -> whale.GetAlertSettingsResponse
	5, // 10: whale.WhaleService.UpdateAlertSettings:output_type -> whale.UpdateAlertSettingsResponse
	7, // 11: whale.WhaleService.HealthCheck:output_type -> whale.HealthCheckResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_whale_proto_init() }
func file_api_proto_whale_proto_init() {
	if File_api_proto_whale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_whale_proto_rawDesc), len(file_api_proto_whale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_whale_proto_goTypes,
		DependencyIndexes: file_api_proto_whale_proto_depIdxs,
		MessageInfos:      file_api_proto_whale_proto_msgTypes,
	}.Build()
	File_api_proto_whale_proto = out.File
	file_api_proto_whale_proto_goTypes = nil
	file_api_proto_whale_proto_depIdxs = nil
}
